# USING NumPy FOR DATA ANALYSIS

In [1]:
import numpy as np

# NumPy Arrays

In [2]:
list1 = [1,2,3]

In [3]:
arr1 = np.array(list1)

### creation of a vector

In [5]:
arr1

array([1, 2, 3])

In [8]:
mat1 = [[1,2,3],[4,5,6],[7,8,9]]

In [11]:
matrix1 = np.array(mat1)

### creation of a matrix

In [10]:
matrix1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Generate numpy arrays automatically

In [13]:
# METHOD 1

np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### - to create array containing only zeros

In [18]:
np.zeros((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

### to create array containing only ones

In [21]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### most used method

In [23]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

## Creating identity matrix
* an identity matrix is a matrix in which the number of rows = the number of columns and there is a diagonal line made of only ones and the rest of the positions are filled with only zeros.

In [25]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Creating an array filled with random numbers

In [26]:
np.random.rand(5) # This creates a vector

array([0.18551698, 0.97876896, 0.64210389, 0.54576411, 0.41828687])

In [27]:
np.random.rand(5,5) # This creates a matrix

array([[0.68598412, 0.06323972, 0.12796618, 0.07076806, 0.66735988],
       [0.55202618, 0.09965386, 0.89853624, 0.39829273, 0.73950774],
       [0.23705609, 0.81777272, 0.60753131, 0.94141792, 0.28244447],
       [0.90285039, 0.44747464, 0.28130659, 0.57514102, 0.22080757],
       [0.54062271, 0.32420651, 0.38484885, 0.83716732, 0.45069919]])

In [30]:
np.random.randn(2)

array([ 1.78416024, -0.30822744])

In [33]:
np.random.randn(4,4)

array([[-0.45767347, -0.94586873,  0.19240554,  0.06854531],
       [-0.08647645, -0.03727138,  0.08335302, -1.02369126],
       [ 0.67729692,  0.2110331 , -1.82560524, -0.05979097],
       [-0.81729886,  0.32953315,  0.08692597,  2.72689397]])

In [36]:
np.random.randint(1,100,10)

array([43, 40, 89, 94, 22, 84, 35, 36, 76, 35])

## Reshaping arrays

In [37]:
arr = np.arange(25)

In [38]:
arr.reshape(5,5) # raise ValueError if the matrix cannot be filled completely

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

## Few useful methods

In [40]:
randarr = np.random.randint(0,100,10)

In [53]:
randarr

array([29, 55, 82, 64, 23, 72, 17, 72, 89, 42])

In [55]:
randarr.max()

89

In [56]:
randarr.min()

17

In [44]:
randarr.argmax()

8

In [47]:
randarr.argmin()

6

In [52]:
randarr.shape

(10,)

In [58]:
randarr.dtype

dtype('int32')

# NumPy Indexing and Listing 

## Vectors

In [60]:
arr = np.arange(0,11)

In [61]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
arr[4]

4

In [64]:
arr[1:5]

array([1, 2, 3, 4])

In [65]:
arr[:5]

array([0, 1, 2, 3, 4])

In [66]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [67]:
arr[:6] = 100

In [68]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [69]:
arr = np.arange(0,11)

In [70]:
slice_ver = arr[:6]
slice_ver

array([0, 1, 2, 3, 4, 5])

In [71]:
slice_ver[:] = 99

In [72]:
slice_ver #This is not a copy of arr. it is just a reference

array([99, 99, 99, 99, 99, 99])

In [73]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [74]:
arr_copy = arr.copy() # this is how you can copy an array

In [76]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [77]:
arr_copy[:] = 100

In [78]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [79]:
arr # original array is unaffected

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Matrix indexing

In [83]:
arr_mat1 = np.array([[5,10,15],[20,25,30], [35,40,45]])

In [84]:
arr_mat1

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [85]:
# There are two methods to index matrices

In [88]:
# First method(Double Bracket format)

arr_mat1[0][0] # returns the number 5 

5

In [93]:
# Second method(Single Bracket format)

arr_mat1[0,0] # also returns the number 5
arr_mat1[1:] # grabs a set of matrices instead of one value

array([[20, 25, 30],
       [35, 40, 45]])

In [96]:
arr_mat1[1, :]

array([20, 25, 30])

In [97]:
# Comparison operators for arrays
arr = np.arange(10)

In [99]:
boolarr1 = arr > 5

In [101]:
arr[boolarr1]

array([6, 7, 8, 9])

# NumPy Operations
* Array and Array
* Array and Scalar
* Universal Array functions

## Array and Array

In [102]:
arr = np.arange(0,11)

In [104]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [105]:
arr + arr  # addition of every term

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [106]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [114]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [115]:
arr/arr

C:\Users\prade\AppData\Local\Temp\ipykernel_1780\1862401812.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [116]:
arr ** arr

array([         1,          1,          4,         27,        256,
             3125,      46656,     823543,   16777216,  387420489,
       1410065408])

## Array and Scalar

In [110]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [111]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [112]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [113]:
arr/100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ])

In [117]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

## Universal Array functions

In [119]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [120]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [121]:
np.log(arr)

C:\Users\prade\AppData\Local\Temp\ipykernel_1780\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])